set nocompatible "不要vim模仿vi模式，建议设置，否则会有很多不兼容的问题
syntax on"打开高亮

set hlsearch "高亮显示结果
set incsearch "在输入要搜索的文字时，vim会实时匹配

set foldmethod=indent
map <F4> zo
map <F3> zR

:set tabstop=4
:set shiftwidth=4
:set expandtab
:set nu

set guifont=Bitstream_Vera_Sans_Mono:h9:cANSI "记住空格用下划线代替哦
set gfw=幼圆:h10:cGB2312

set backspace=indent,eol,start whichwrap+=<,>,[,] "允许退格键的使用
